### PR TITLE
Add troubleshooting section to readme for uinput related error.

### PR DESCRIPTION
**Pull request by CoryParsnipson**
I encountered the same symptoms as the user who opened issue #69 and I managed to find a solution for it. I've added a little section to the README.rst that describes what I did to resolve it.

### CODE REVIEW

**Comment by Ape** [comment]
I reopened the issue as it can be fixed with documentation. Please add "Resolves #69." to your commit message body.

**Comment by Ape** [comment]
Please refer to the Permissions section of the README since the problem might also be caused by insufficient permissions.

The formatting can be improved. Please see the preview: https://github.com/CoryParsnipson/ds4drv/blob/e75fb830115e384f9b497e12f59151b0774e3172/README.rst#troubleshooting

The commands and filenames should look something like `this`. In addition there should be a subheader like the following:

Troubleshooting
----------------------

### Failed to create input device: "/dev/uinput" cannot be opened for writing
This could be because [...]

**Comment by CoryParsnipson** [comment]
Hi, I've added all your suggestions. I'm running into an issue where I cannot get the "Failed to create [..]" line on the correct subtitle level, even though I'm using the ^ underline. What do you think?

**Comment by Ape** [comment]
Hmm, weird. Try if if helps if you add some extra new lines, or maybe just some text between the titles. Or is the title just too long?

There is this unmatched parenthesis. I think it doesn't need the parentheses at all. The sentence could also be phrased a bit shorter. E.g. "Install `uinput` on your distro's package manager if needed".

**Comment by CoryParsnipson** [comment]
I thought the title was too long at first, but shortening it did not help the issue *sometimes*. I decided to add a little text between "Troubleshooting" and the subtitle. Hope that is acceptable?

Also, I fixed the unmatched parenthesis, thanks!

**Comment by Ape** [comment]
Looking good now. Could you modify the commit message to be like this:

```
Add troubleshooting section to readme for uinput related error

Resolves #69.
```

I.e. no dot at the end of subject and "Resolves" moved to the body.

**Comment by CoryParsnipson** [comment]
Done!

**Comment by Ape** [comment]
Thanks!

**Pull request merged**
